services:

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: 01Blog_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - net_bridge_b
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d 01Blog_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      # network: host
    container_name: backend-app
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      APP_DEFAULT_ADMIN_PASSWORD: ${APP_DEFAULT_ADMIN_PASSWORD}
      APP_DEFAULT_USER_PASSWORD: ${APP_DEFAULT_USER_PASSWORD}
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./Backend/uploads:/app/uploads
    networks:
      - net_bridge_b
      - net_bridge_a
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # network: host
    container_name: blog_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - net_bridge_a
    restart: always

networks:
  net_bridge_a:
    driver: bridge
    

  net_bridge_b:
    driver: bridge
    internal: true